name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновляем до v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Обновляем до v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create test-results directory
        run: mkdir -p test-results  # Создаём директорию для отчётов

      - name: Run tests
        run: |
          pytest test_script.py --junitxml=test-results/report.xml
        continue-on-error: true  # Продолжаем даже при ошибке тестов

      - name: Upload test results
        if: always()  # Выполняется всегда, даже если тесты упали
        uses: actions/upload-artifact@v4  # Обновляем до v4
        with:
          name: test-results
          path: test-results/report.xml
